// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyhkgikeinzjlxipumnb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aGtnaWtlaW56amx4aXB1bW5iIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk4MjcxNzIsImV4cCI6MjA2NTQwMzE3Mn0.VDhEbsHtHYyG2voyqUjJ0Q7clVgmbWKktkxf6ARhd1s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);