// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahpmeszqhkghwlrnoira.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFocG1lc3pxaGtnaHdscm5vaXJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDI3NTQsImV4cCI6MjA2NTU3ODc1NH0.ZVbUQMGVdK0iKyp_7PMXlwBlglaIxtVlueGHzrWeVXI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);